[package]
name = "terminal_input"
version = "0.1.1"
authors = ["thomasm <thomas@mundar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios="0.3"
phf={ version="0.8.0", features = ["macros"] }
